/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as BecomeProviderRouteImport } from './routes/become-provider'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIdRouteImport } from './routes/services.$id'
import { Route as DashboardProviderRouteImport } from './routes/dashboard.provider'
import { Route as DashboardCustomerRouteImport } from './routes/dashboard.customer'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const BecomeProviderRoute = BecomeProviderRouteImport.update({
  id: '/become-provider',
  path: '/become-provider',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIdRoute = ServicesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ServicesRoute,
} as any)
const DashboardProviderRoute = DashboardProviderRouteImport.update({
  id: '/dashboard/provider',
  path: '/dashboard/provider',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardCustomerRoute = DashboardCustomerRouteImport.update({
  id: '/dashboard/customer',
  path: '/dashboard/customer',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/become-provider': typeof BecomeProviderRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/become-provider': typeof BecomeProviderRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/become-provider': typeof BecomeProviderRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/services': typeof ServicesRouteWithChildren
  '/signup': typeof SignupRoute
  '/dashboard/admin': typeof DashboardAdminRoute
  '/dashboard/customer': typeof DashboardCustomerRoute
  '/dashboard/provider': typeof DashboardProviderRoute
  '/services/$id': typeof ServicesIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/become-provider'
    | '/login'
    | '/onboarding'
    | '/services'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/customer'
    | '/dashboard/provider'
    | '/services/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/become-provider'
    | '/login'
    | '/onboarding'
    | '/services'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/customer'
    | '/dashboard/provider'
    | '/services/$id'
  id:
    | '__root__'
    | '/'
    | '/become-provider'
    | '/login'
    | '/onboarding'
    | '/services'
    | '/signup'
    | '/dashboard/admin'
    | '/dashboard/customer'
    | '/dashboard/provider'
    | '/services/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BecomeProviderRoute: typeof BecomeProviderRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SignupRoute: typeof SignupRoute
  DashboardAdminRoute: typeof DashboardAdminRoute
  DashboardCustomerRoute: typeof DashboardCustomerRoute
  DashboardProviderRoute: typeof DashboardProviderRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/become-provider': {
      id: '/become-provider'
      path: '/become-provider'
      fullPath: '/become-provider'
      preLoaderRoute: typeof BecomeProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/$id': {
      id: '/services/$id'
      path: '/$id'
      fullPath: '/services/$id'
      preLoaderRoute: typeof ServicesIdRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/dashboard/provider': {
      id: '/dashboard/provider'
      path: '/dashboard/provider'
      fullPath: '/dashboard/provider'
      preLoaderRoute: typeof DashboardProviderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/customer': {
      id: '/dashboard/customer'
      path: '/dashboard/customer'
      fullPath: '/dashboard/customer'
      preLoaderRoute: typeof DashboardCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface ServicesRouteChildren {
  ServicesIdRoute: typeof ServicesIdRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesIdRoute: ServicesIdRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BecomeProviderRoute: BecomeProviderRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SignupRoute: SignupRoute,
  DashboardAdminRoute: DashboardAdminRoute,
  DashboardCustomerRoute: DashboardCustomerRoute,
  DashboardProviderRoute: DashboardProviderRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
